services:
  - type: web
    name: n8n
    env: docker
    plan: free
    autoDeploy: false
    envVars:
      - key: N8N_BASIC_AUTH_USER
        value: admin
      - key: N8N_BASIC_AUTH_PASSWORD
        value: yourpassword
      - key: N8N_HOST
        value: n8n.onrender.com
      - key: WEBHOOK_TUNNEL_URL
        value: https://n8n.onrender.com
